# Generated by Django 5.2.4 on 2025-08-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
