# Generated by Django 5.2.8 on 2025-12-25 18:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='price_per_gram_snapshot',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity_grams',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
