# Generated by Django 5.2.8 on 2026-01-10 16:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_steps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='stove_type',
            field=models.CharField(blank=True, choices=[('electric', 'เตาไฟฟ้า'), ('induction', 'เตาแม่เหล็กไฟฟ้า (Induction)'), ('gas', 'เตาแก๊ส')], default=None, help_text='ถ้าไม่เลือก ระบบจะใช้ค่า default จากการตั้งค่าผู้ใช้', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='UserCookingCostSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('basic', 'Basic (เฉลี่ย)'), ('advanced', 'Advanced (คิดตามเตา/เวลา)')], default='basic', max_length=20)),
                ('seasoning_cost_per_serving', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('overhead_cost_per_serving', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=10)),
                ('default_stove_type', models.CharField(choices=[('electric', 'เตาไฟฟ้า'), ('induction', 'เตาแม่เหล็กไฟฟ้า (Induction)'), ('gas', 'เตาแก๊ส')], default='electric', max_length=20)),
                ('default_cook_minutes', models.PositiveIntegerField(default=10)),
                ('electricity_rate_per_kwh', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=10)),
                ('electric_power_watt', models.PositiveIntegerField(default=1200)),
                ('induction_power_watt', models.PositiveIntegerField(default=1500)),
                ('gas_cost_per_hour', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_cost_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User cooking cost setting',
                'verbose_name_plural': 'User cooking cost settings',
            },
        ),
    ]
