# Generated by Django 5.2.4 on 2025-09-03 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menu_options_menu_restaurant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='status',
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredients',
            field=models.TextField(blank=True, help_text='เช่น: กะเพรา, หมู, พริก, กระเทียม, ไข่'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_halal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='no_alcohol',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
