# Generated by Django 5.2.4 on 2025-09-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menu_approved_at_menu_approved_by_menu_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
