# Generated by Django 5.2.6 on 2025-09-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_alter_menu_description_alter_menu_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='menus', to='menus.ingredient'),
        ),
    ]
