# Generated by Django 5.2.8 on 2025-12-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_ingredient_remove_menu_ingredients_menu_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price_per_gram',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='size_grams',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='source',
            field=models.CharField(default='lotus', max_length=50),
        ),
    ]
